# Generated by Django 4.2.6 on 2024-07-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_product_name', models.CharField(max_length=100)),
                ('cart_product_price', models.FloatField(max_length=100)),
                ('cart_product_discount', models.FloatField(max_length=100)),
            ],
        ),
    ]
