# Generated by Django 4.2.6 on 2024-07-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_data',
            name='cart_product_total',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
