# Generated by Django 4.2.6 on 2024-07-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
