# Generated by Django 4.2.6 on 2024-07-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales_by_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_amount', models.IntegerField()),
                ('expense_amount', models.IntegerField()),
                ('register_amount', models.IntegerField()),
            ],
        ),
    ]
