# Generated by Django 4.2.6 on 2024-07-08 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_sales_by_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_by_date',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
