# Generated by Django 4.2.6 on 2024-07-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_sales_by_date_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_by_date',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
