# Generated by Django 4.2.6 on 2024-07-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_alter_sales_by_date_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sale_upi',
            field=models.BooleanField(default=False),
        ),
    ]
