# Generated by Django 4.2.6 on 2024-07-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_sales_sale_upi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_by_date',
            name='upi_amount',
            field=models.IntegerField(default=0),
        ),
    ]
