# Generated by Django 4.2.6 on 2024-07-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_sales_by_date_upi_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=100)),
                ('expense_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_product_name', models.CharField(max_length=100)),
                ('sale_product_price', models.FloatField()),
                ('sale_product_discount', models.FloatField()),
                ('sale_product_total', models.FloatField()),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('sale_upi', models.BooleanField(default=False)),
            ],
        ),
    ]
